sudo: required
services:
  - docker
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud componets update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  
  
# This is fix. I was see this in lecture 260
script: - docker run -e CI=true USERNAME/docker-react npm run test